### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by Donis2** [charlesix59/chinese_word_rhyme#1]
感谢兄弟对诗词数据化做的贡献，我正在写一个诗词网站，感谢你为我解决难题

**Comment by charlesix59** [comment]
> 感谢兄弟对诗词数据化做的贡献，我正在写一个诗词网站，感谢你为我解决难题

感谢认可，如果有别的需要可以给我提issue，我将尽可能的支持🥳

**Comment by Donis2** [comment]
你好，请问你开发过诗词格律检测一类的工具吗
